---
- name: Ensure gtar and unzip are installed.
  openbsd_pkg: "name={{ item }} state=present"
  with_items:
    - gtar--
    - unzip--

- name: Obtain version number.
  shell: uname -r |sed 's/\.//'
  register: ver
  changed_when: False

- name: Extract xbase if necessary.
  unarchive:
    src: ftp://{{ mirror }}/pub/OpenBSD/{{ ansible_distribution_version }}/{{ ansible_architecture }}/xbase{{ ver.stdout }}.tgz
    dest: /
    creates: /usr/X11R6/lib/libfreetype.a
    remote_src: yes

- name: Ensure Java is installed.
  openbsd_pkg: "name={{ item }} state=latest"
  with_items: "{{ java_packages }}"
 
