---
- name: Ensure gtar and unzip are installed.
  openbsd_pkg: "name={{ item }} state=present"
  with_items:
    - gtar--
    - unzip--

- name: Obtain version number.
  shell: uname -r |sed 's/\.//'
  register: ver
  changed_when: False

- name: Extract xbase if necessary.
  unarchive:
    src: ftp://{{ mirror }}/pub/OpenBSD/{{ ansible_distribution_version }}/{{ ansible_architecture }}/xbase{{ ver.stdout }}.tgz
    dest: /
    creates: /usr/X11R6/lib/libfreetype.a
    remote_src: yes

- name: Ensure Java is installed.
  openbsd_pkg: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"
 
- name: Set JAVA_HOME if configured.
  lineinfile: dest=/etc/profile
    regexp=''
    insertafter=EOF
    line='export JAVA_HOME={{ java_home }}'
    state=present
    create=True
  when: java_home is defined and java_home != '' and ansible_os_family == 'OpenBSD'

